---                                             
- name: test 
  hosts: localhost                              
  remote_user: "ubuntu"                                             
  tasks:                                        
    - name: test my_pluging 
      debug: msg={{ lookup('my_pluging') }} 