---                                             
- name: test 
  hosts: localhost                              
                                               
  tasks:                                        
    - name: test my_pluging 
      debug: msg={{ lookup('my_pluging') }} 