---                                             
- name: test 
  hosts: all
  gather_facts: "true"                             
  remote_user: "ubuntu"                                             
  tasks:                                        
    - name: test ppk
      debug: msg={{ lookup('tss', 3489) }}