---
- name: "Included Role - ahuffman.resolv for WP Test"
  hosts: "test"
  vars:
    contents: "{{ lookup('thycotic_secret', thycotic_config='thycotic', secret=3491, field='private-key') }}"
    tasks:
      - include_vars:
            file: thycotic_sdk_config.yml
            name: thycotic
  remote_user: "root"
  tasks:
    - name: "Configure resolv.conf"
      include_role:
        name: "ahuffman.resolv"
      vars:
        resolv_nameservers:
          - "10.10.92.11"
          - "10.10.24.24"
          - "10.64.111.7"
        resolv_search:
          - "wpprivate.com"
          - "washpost.com"
          - "washingtonpost.com"
