---
- name: "Configure resolv.conf"
  hosts: "ubuntutest"
  remote_user: "ubuntu"
  vars:
        contents: "{{ lookup('thycotic_secret', 'thycotic', secret='3491', field='private-key') }}"
  tasks:
      - include_vars:
            file: thycotic_sdk_config.yml
            name: thycotic
        include_role:
          name: "ahuffman.resolv"
          resolv_nameservers:
            - "10.10.92.11"
            - "10.10.24.24"
            - "10.64.111.7"
          resolv_search:
            - "wpprivate.com"
            - "washpost.com"
            - "washingtonpost.com"