---
- hosts: localhost
    vars:
        contents: "{{ lookup('thycotic_secret', thycotic_config='thycotic', secret=4, field='password'") }}
    tasks:
      - include_vars:
            file: thycotic_sdk_config.yml
            name: thycotic