---
- name: "Included Role - ahuffman.resolv for WP Test"
  hosts: "test"
  tasks:
    - name: "Configure resolv.conf"
      include_role:
        name: "ahuffman.resolv"
      vars:
        resolv_nameservers:
          - "10.10.92.11"
          - "10.10.24.24"
          - "10.64.111.7"
        resolv_search:
          - "wpprivate.com"
          - "washpost.com"
          - "washingtonpost.com"
