---
- hosts: all 
  vars:
      secret: "{{ lookup('tss', 3488) }}"
  tasks:
      - debug: msg="the password is {{ (secret['items'] | items2dict(key_name='slug', value_name='itemValue'))['password'] }}"